In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("../data/crop_prices.csv")
df.

,state,district,market,commodity,variety,arrival_date,min_price,max_price,modal_price
0,Andaman and Nicobar,South Andaman,Port Blair,Amaranthus,Amaranthus,04/03/2019,6000,8000,7000
1,Andaman and Nicobar,South Andaman,Port Blair,Banana - Green,Banana - Green,04/03/2019,4500,5500,5000
2,Andaman and Nicobar,South Andaman,Port Blair,Bhindi(Ladies Finger),Bhindi,04/03/2019,6000,8000,7000
3,Andaman and Nicobar,South Andaman,Port Blair,Bitter gourd,Other,04/03/2019,6000,8000,7000
4,Andaman and Nicobar,South Andaman,Port Blair,Black pepper,Other,04/03/2019,110000,130000,120000

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2238 entries, 0 to 2237
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         2238 non-null   str
 1   district      2238 non-null   str
 2   market        2238 non-null   str
 3   commodity     2238 non-null   str
 4   variety       2238 non-null   str
 5   arrival_date  2238 non-null   str
 6   min_price     2238 non-null   int64
 7   max_price     2238 non-null   int64
 8   modal_price   2238 non-null   int64
dtypes: int64(3), str(6)
memory usage: 157.5 KB

In [3]:
df.isna().sum()

state           0
district        0
market          0
commodity       0
variety         0
arrival_date    0
min_price       0
max_price       0
modal_price     0
dtype: int64

In [6]:
df['arrival_date'] = pd.to_datetime(df['arrival_date'], dayfirst=True)

df['month'] = df['arrival_date'].dt.month
df['year'] = df['arrival_date'].dt.year
df[['arrival_date', 'month', 'year']].head()

  arrival_date  month  year
0   2019-03-04      3  2019
1   2019-03-04      3  2019
2   2019-03-04      3  2019
3   2019-03-04      3  2019
4   2019-03-04      3  2019

In [8]:
from sklearn.preprocessing import LabelEncoder

le_state = LabelEncoder()
le_market = LabelEncoder()
le_commodity = LabelEncoder()

df['state'] = le_state.fit_transform(df['state'])
df['market'] = le_market.fit_transform(df['market'])
df['commodity'] = le_commodity.fit_transform(df['commodity'])
X = df[['state', 'market', 'commodity', 'month', 'year']]
y = df['modal_price']

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(n_estimators=50, random_state=42)
model.fit(X_train, y_train)

preds = model.predict(X_test)
mse = mean_squared_error(y_test, preds)
rmse = mse ** 0.5
rmse

1701.6009708787196